window.DECKS = [
  { id: "b1b2",    level: "B1 — B2",      title: "Слова · средний",       count: 24, known: 7, active: true },
  { id: "c1c2",    level: "C1 — C2",      title: "Слова · продвинутый",   count: 18, known: 0, active: false },
  { id: "phrasal", level: "Phrasal",      title: "Фразовые глаголы",      count: 12, known: 0, active: false },
  { id: "colloc",  level: "Collocations", title: "Устойчивые выражения",  count: 9,  known: 0, active: false },
  { id: "idioms",  level: "Idioms",       title: "Идиомы",                count: 6,  known: 0, active: false },
];

// Структура карточки:
//   front:  example
//   back:   forms [V1,V2,V3], formUsed, ru, film, character
window.WORD_DECK = [
  {
    example: "Put some pressure on him.",
    forms: ["put", "put", "put"],
    formUsed: "V1 (Present / Base)",
    ru: "Надави на него",
    film: "The Godfather",
    character: "Майкл Корлеоне",
  },
  {
    example: "You put me in a difficult position.",
    forms: ["put", "put", "put"],
    formUsed: "V2 (Past)",
    ru: "Ты поставил меня в сложное положение",
    film: "The Dark Knight",
    character: "Джокер",
  },
  {
    example: "The plan is put on hold.",
    forms: ["put", "put", "put"],
    formUsed: "V3 (состояние)",
    ru: "План находится на паузе",
    film: "Mission: Impossible",
    character: "",
  },
  {
    example: "Leave me alone.",
    forms: ["leave", "left", "left"],
    formUsed: "V1 (Present / Base)",
    ru: "Оставь меня в покое",
    film: "Titanic",
    character: "Роза",
  },
  {
    example: "He left us.",
    forms: ["leave", "left", "left"],
    formUsed: "V2 (Past)",
    ru: "Он ушёл / покинул нас",
    film: "The Dark Knight",
    character: "Харви Дент",
  },
  {
    example: "He is left alone.",
    forms: ["leave", "left", "left"],
    formUsed: "V3 (состояние)",
    ru: "Он остался один",
    film: "Cast Away",
    character: "",
  },
  {
    example: "Think about it.",
    forms: ["think", "thought", "thought"],
    formUsed: "V1 (Present / Base)",
    ru: "Подумай об этом",
    film: "The Matrix",
    character: "Морфеус",
  },
  {
    example: "I thought you were dead.",
    forms: ["think", "thought", "thought"],
    formUsed: "V2 (Past)",
    ru: "Я думал, что ты мёртв",
    film: "Inception",
    character: "Кобб",
  },
  {
    example: "The idea is thought through.",
    forms: ["think", "thought", "thought"],
    formUsed: "V3 (состояние)",
    ru: "Идея продумана",
    film: "A Beautiful Mind",
    character: "",
  },
  {
    example: "Come with me.",
    forms: ["come", "came", "come"],
    formUsed: "V1 (Present / Base)",
    ru: "Пойдём со мной",
    film: "Terminator 2: Judgment Day",
    character: "Терминатор (Арнольд Шварценеггер)",
  },
  {
    example: "You came back.",
    forms: ["come", "came", "come"],
    formUsed: "V2 (Past)",
    ru: "Ты вернулся",
    film: "Interstellar",
    character: "Купер (Мэттью Макконахи)",
  },
  {
    example: "Winter has come.",
    forms: ["come", "came", "come"],
    formUsed: "V3 (состояние)",
    ru: "Зима наступила",
    film: "Game of Thrones",
    character: "",
  },
  {
    example: "Find the truth.",
    forms: ["find", "found", "found"],
    formUsed: "V1 (Present / Base)",
    ru: "Найди правду",
    film: "Se7en",
    character: "детектив Сомерсет",
  },
  {
    example: "I found the answer.",
    forms: ["find", "found", "found"],
    formUsed: "V2 (Past)",
    ru: "Я нашёл ответ",
    film: "The Da Vinci Code",
    character: "Роберт Лэнгдон",
  },
  {
    example: "The evidence is found.",
    forms: ["find", "found", "found"],
    formUsed: "V3 (состояние)",
    ru: "Доказательство найдено",
    film: "Spotlight",
    character: "",
  },
  {
    example: "Show me the money.",
    forms: ["show", "showed", "shown"],
    formUsed: "V1 (Present / Base)",
    ru: "Покажи деньги",
    film: "Jerry Maguire",
    character: "Род Тидвелл",
  },
  {
    example: "He showed no mercy.",
    forms: ["show", "showed", "shown"],
    formUsed: "V2 (Past)",
    ru: "Он не проявил пощады",
    film: "Gladiator",
    character: "Коммод",
  },
  {
    example: "The truth is shown.",
    forms: ["show", "showed", "shown"],
    formUsed: "V3 (состояние)",
    ru: "Правда раскрыта",
    film: "V for Vendetta",
    character: "",
  },
  {
    example: "I take responsibility for my actions.",
    forms: ["take", "took", "taken"],
    formUsed: "V1 (Present / Base)",
    ru: "Я беру ответственность за свои действия",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "I took the money and ran.",
    forms: ["take", "took", "taken"],
    formUsed: "V2 (Past)",
    ru: "Я взял деньги и убежал",
    film: "Pulp Fiction",
    character: "Pumpkin (Ringo)",
  },
  {
    example: "The hostages are taken.",
    forms: ["take", "took", "taken"],
    formUsed: "V3 (состояние)",
    ru: "Заложники захвачены",
    film: "Taken",
    character: "Bryan Mills",
  },
  {
    example: "I won't let you down.",
    forms: ["let", "let", "let"],
    formUsed: "V1 (Present / Base)",
    ru: "Я тебя не подведу",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "He let her go.",
    forms: ["let", "let", "let"],
    formUsed: "V2 (Past)",
    ru: "Он отпустил её",
    film: "Titanic",
    character: "Jack Dawson",
  },
  {
    example: "You are let inside.",
    forms: ["let", "let", "let"],
    formUsed: "V3 (состояние)",
    ru: "Тебя впустили",
    film: "Harry Potter and the Philosopher's Stone",
    character: "Rubeus Hagrid",
  },
  {
    example: "I set my own rules.",
    forms: ["set", "set", "set"],
    formUsed: "V1 (Present / Base)",
    ru: "Я устанавливаю свои правила",
    film: "Iron Man",
    character: "Tony Stark",
  },
  {
    example: "He set the plan in motion.",
    forms: ["set", "set", "set"],
    formUsed: "V2 (Past)",
    ru: "Он привёл план в действие",
    film: "The Dark Knight",
    character: "Joker",
  },
  {
    example: "The trap is set.",
    forms: ["set", "set", "set"],
    formUsed: "V3 (состояние)",
    ru: "Ловушка установлена",
    film: "Home Alone",
    character: "Kevin McCallister",
  },
  {
    example: "I read everything I can find.",
    forms: ["read", "read", "read"],
    formUsed: "V1 (Present / Base)",
    ru: "Я читаю всё, что могу найти",
    film: "Harry Potter and the Philosopher's Stone",
    character: "Hermione Granger",
  },
  {
    example: "I read[red] your file.",
    forms: ["read", "read", "read"],
    formUsed: "V2 (Past)",
    ru: "Я прочитал твоё досье",
    film: "The Matrix",
    character: "Agent Smith",
  },
  {
    example: "The message is read[red].",
    forms: ["read", "read", "read"],
    formUsed: "V3 (состояние)",
    ru: "Сообщение прочитано",
    film: "Sherlock Holmes",
    character: "Sherlock Holmes",
  },
  {
    example: "I light the fire every night.",
    forms: ["light", "lit", "lit"],
    formUsed: "V1 (Present / Base)",
    ru: "Я зажигаю огонь каждую ночь",
    film: "The Revenant",
    character: "Hugh Glass",
  },
  {
    example: "He lit the match.",
    forms: ["light", "lit", "lit"],
    formUsed: "V2 (Past)",
    ru: "Он зажёг спичку",
    film: "The Dark Knight",
    character: "Joker",
  },
  {
    example: "The room is lit.",
    forms: ["light", "lit", "lit"],
    formUsed: "V3 (состояние)",
    ru: "Комната освещена",
    film: "John Wick",
    character: "John Wick",
  },
  {
    example: "I keep my promises.",
    forms: ["keep", "kept", "kept"],
    formUsed: "V1 (Present / Base)",
    ru: "Я держу свои обещания",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "I kept the secret.",
    forms: ["keep", "kept", "kept"],
    formUsed: "V2 (Past)",
    ru: "Я сохранил секрет",
    film: "Harry Potter and the Deathly Hallows: Part 2",
    character: "Severus Snape",
  },
  {
    example: "The door is kept locked.",
    forms: ["keep", "kept", "kept"],
    formUsed: "V3 (состояние)",
    ru: "Дверь держат запертой",
    film: "Jurassic Park",
    character: "John Hammond",
  },
  {
    example: "I learn fast.",
    forms: ["learn", "learnt", "learnt"],
    formUsed: "V1 (Present / Base)",
    ru: "Я быстро учусь",
    film: "The Matrix",
    character: "Neo",
  },
  {
    example: "I learnt the truth.",
    forms: ["learn", "learnt", "learnt"],
    formUsed: "V2 (Past)",
    ru: "Я узнал правду",
    film: "Star Wars: Episode V – The Empire Strikes Back",
    character: "Luke Skywalker",
  },
  {
    example: "The lesson is learnt.",
    forms: ["learn", "learnt", "learnt"],
    formUsed: "V3 (состояние)",
    ru: "Урок усвоен",
    film: "Batman Begins",
    character: "Bruce Wayne",
  },
  {
    example: "I can do this all day.",
    forms: ["can", "could", "could"],
    formUsed: "V1 (Present / Base)",
    ru: "Я могу делать это весь день",
    film: "Captain America: The First Avenger",
    character: "Steve Rogers",
  },
  {
    example: "I could save her.",
    forms: ["can", "could", "could"],
    formUsed: "V2 (Past)",
    ru: "Я мог её спасти",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "It could be done.",
    forms: ["can", "could", "could"],
    formUsed: "V3 (состояние)",
    ru: "Это могло быть сделано",
    film: "Inception",
    character: "Dom Cobb",
  },
  {
    example: "I may be able to help you.",
    forms: ["may", "might", "might"],
    formUsed: "V1 (Present / Base)",
    ru: "Возможно, я смогу тебе помочь",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Gandalf",
  },
  {
    example: "It might work.",
    forms: ["may", "might", "might"],
    formUsed: "V2 (Past)",
    ru: "Это могло бы сработать",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "It might be done.",
    forms: ["may", "might", "might"],
    formUsed: "V3 (состояние)",
    ru: "Это могло быть сделано",
    film: "Inception",
    character: "Dom Cobb",
  },
  {
    example: "I get what you mean.",
    forms: ["get", "got", "got"],
    formUsed: "V1 (Present / Base)",
    ru: "Я понимаю, что ты имеешь в виду",
    film: "The Matrix",
    character: "Neo",
  },
  {
    example: "I got the message.",
    forms: ["get", "got", "got"],
    formUsed: "V2 (Past)",
    ru: "Я получил сообщение",
    film: "John Wick",
    character: "John Wick",
  },
  {
    example: "The job is got.",
    forms: ["get", "got", "got"],
    formUsed: "V3 (состояние)",
    ru: "Работа получена",
    film: "The Wolf of Wall Street",
    character: "Jordan Belfort",
  },
  {
    example: "I have a plan.",
    forms: ["have", "had", "had"],
    formUsed: "V1 (Present / Base)",
    ru: "У меня есть план",
    film: "The Dark Knight",
    character: "Joker",
  },
  {
    example: "I had a choice.",
    forms: ["have", "had", "had"],
    formUsed: "V2 (Past)",
    ru: "У меня был выбор",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "The problem is had.",
    forms: ["have", "had", "had"],
    formUsed: "V3 (состояние)",
    ru: "Проблема уже имелась",
    film: "The Matrix Reloaded",
    character: "Neo",
  },
  {
    example: "I hear everything.",
    forms: ["hear", "heard", "heard"],
    formUsed: "V1 (Present / Base)",
    ru: "Я слышу всё",
    film: "The Dark Knight",
    character: "Lucius Fox",
  },
  {
    example: "I heard a noise.",
    forms: ["hear", "heard", "heard"],
    formUsed: "V2 (Past)",
    ru: "Я услышал шум",
    film: "A Quiet Place",
    character: "Lee Abbott",
  },
  {
    example: "The signal is heard.",
    forms: ["hear", "heard", "heard"],
    formUsed: "V3 (состояние)",
    ru: "Сигнал услышан",
    film: "Interstellar",
    character: "Cooper",
  },
  {
    example: "I say we go now.",
    forms: ["say", "said", "said"],
    formUsed: "V1 (Present / Base)",
    ru: "Я говорю, что нам нужно идти сейчас",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Aragorn",
  },
  {
    example: "He said too much.",
    forms: ["say", "said", "said"],
    formUsed: "V2 (Past)",
    ru: "Он сказал слишком много",
    film: "The Godfather",
    character: "Michael Corleone",
  },
  {
    example: "It is said that he never sleeps.",
    forms: ["say", "said", "said"],
    formUsed: "V3 (состояние)",
    ru: "Говорят, что он никогда не спит",
    film: "John Wick",
    character: "Viggo Tarasov",
  },
  {
    example: "I tell the truth.",
    forms: ["tell", "told", "told"],
    formUsed: "V1 (Present / Base)",
    ru: "Я говорю правду",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "I told you everything.",
    forms: ["tell", "told", "told"],
    formUsed: "V2 (Past)",
    ru: "Я рассказал тебе всё",
    film: "Titanic",
    character: "Rose DeWitt Bukater",
  },
  {
    example: "The story is told.",
    forms: ["tell", "told", "told"],
    formUsed: "V3 (состояние)",
    ru: "История рассказана",
    film: "Forrest Gump",
    character: "Forrest Gump",
  },
  {
    example: "I begin when you're ready.",
    forms: ["begin", "began", "begun"],
    formUsed: "V1 (Present / Base)",
    ru: "Я начинаю, когда ты готов",
    film: "Inception",
    character: "Dom Cobb",
  },
  {
    example: "It all began here.",
    forms: ["begin", "began", "begun"],
    formUsed: "V2 (Past)",
    ru: "Всё началось здесь",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Galadriel",
  },
  {
    example: "The game has begun.",
    forms: ["begin", "began", "begun"],
    formUsed: "V3 (состояние)",
    ru: "Игра началась",
    film: "Sherlock Holmes",
    character: "Sherlock Holmes",
  },
  {
    example: "I do what I have to do.",
    forms: ["do", "did", "done"],
    formUsed: "V1 (Present / Base)",
    ru: "Я делаю то, что должен",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "I did everything right.",
    forms: ["do", "did", "done"],
    formUsed: "V2 (Past)",
    ru: "Я всё сделал правильно",
    film: "Breaking Bad",
    character: "Walter White",
  },
  {
    example: "The job is done.",
    forms: ["do", "did", "done"],
    formUsed: "V3 (состояние)",
    ru: "Работа завершена",
    film: "John Wick",
    character: "John Wick",
  },
  {
    example: "I give you my word.",
    forms: ["give", "gave", "given"],
    formUsed: "V1 (Present / Base)",
    ru: "Я даю тебе своё слово",
    film: "The Lord of the Rings: The Two Towers",
    character: "Aragorn",
  },
  {
    example: "I gave him a chance.",
    forms: ["give", "gave", "given"],
    formUsed: "V2 (Past)",
    ru: "Я дал ему шанс",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "The order is given.",
    forms: ["give", "gave", "given"],
    formUsed: "V3 (состояние)",
    ru: "Приказ отдан",
    film: "Gladiator",
    character: "Maximus",
  },
  {
    example: "I go where I'm needed.",
    forms: ["go", "went", "gone"],
    formUsed: "V1 (Present / Base)",
    ru: "Я иду туда, где я нужен",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "I went back for you.",
    forms: ["go", "went", "gone"],
    formUsed: "V2 (Past)",
    ru: "Я вернулся за тобой",
    film: "Titanic",
    character: "Jack Dawson",
  },
  {
    example: "He is gone.",
    forms: ["go", "went", "gone"],
    formUsed: "V3 (состояние)",
    ru: "Он ушёл",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Aragorn",
  },
  {
    example: "I know what you did.",
    forms: ["know", "knew", "known"],
    formUsed: "V1 (Present / Base)",
    ru: "Я знаю, что ты сделал",
    film: "Sherlock Holmes",
    character: "Sherlock Holmes",
  },
  {
    example: "I knew it.",
    forms: ["know", "knew", "known"],
    formUsed: "V2 (Past)",
    ru: "Я так и знал",
    film: "The Matrix",
    character: "Neo",
  },
  {
    example: "It is known.",
    forms: ["know", "knew", "known"],
    formUsed: "V3 (состояние)",
    ru: "Это известно",
    film: "Game of Thrones",
    character: "Khal Drogo",
  },
  {
    example: "I see dead people.",
    forms: ["see", "saw", "seen"],
    formUsed: "V1 (Present / Base)",
    ru: "Я вижу мёртвых людей",
    film: "The Sixth Sense",
    character: "Cole Sear",
  },
  {
    example: "I saw him.",
    forms: ["see", "saw", "seen"],
    formUsed: "V2 (Past)",
    ru: "Я видел его",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Frodo Baggins",
  },
  {
    example: "He is seen as a hero.",
    forms: ["see", "saw", "seen"],
    formUsed: "V3 (состояние)",
    ru: "Его считают героем",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "I write my own story.",
    forms: ["write", "wrote", "written"],
    formUsed: "V1 (Present / Base)",
    ru: "Я пишу свою собственную историю",
    film: "Joker",
    character: "Arthur Fleck",
  },
  {
    example: "I wrote it down.",
    forms: ["write", "wrote", "written"],
    formUsed: "V2 (Past)",
    ru: "Я это записал",
    film: "Sherlock Holmes",
    character: "Dr. John Watson",
  },
  {
    example: "The letter is written.",
    forms: ["write", "wrote", "written"],
    formUsed: "V3 (состояние)",
    ru: "Письмо написано",
    film: "Pride & Prejudice",
    character: "Mr. Darcy",
  },
];
