window.DECKS = [
  { id: "b1b2",    level: "B1 — B2",      title: "Слова · средний",       count: 24, known: 7, active: true },
  { id: "c1c2",    level: "C1 — C2",      title: "Слова · продвинутый",   count: 18, known: 0, active: false },
  { id: "seg1",    level: "S01 · E01",    title: "Первые 10 мин · всё",   count: 75, known: 0, active: true  },
];

// Структура карточки:
//   front:  example
//   back:   forms [V1,V2,V3], formUsed, ru, film, character
window.WORD_DECK = [
  {
    example: "Put some pressure on him.",
    forms: ["put", "put", "put"],
    formUsed: "V1 (Present / Base)",
    ru: "Надави на него",
    film: "The Godfather",
    character: "Майкл Корлеоне",
  },
  {
    example: "You put me in a difficult position.",
    forms: ["put", "put", "put"],
    formUsed: "V2 (Past)",
    ru: "Ты поставил меня в сложное положение",
    film: "The Dark Knight",
    character: "Джокер",
  },
  {
    example: "The plan is put on hold.",
    forms: ["put", "put", "put"],
    formUsed: "V3 (состояние)",
    ru: "План находится на паузе",
    film: "Mission: Impossible",
    character: "",
  },
  {
    example: "Leave me alone.",
    forms: ["leave", "left", "left"],
    formUsed: "V1 (Present / Base)",
    ru: "Оставь меня в покое",
    film: "Titanic",
    character: "Роза",
  },
  {
    example: "He left us.",
    forms: ["leave", "left", "left"],
    formUsed: "V2 (Past)",
    ru: "Он ушёл / покинул нас",
    film: "The Dark Knight",
    character: "Харви Дент",
  },
  {
    example: "He is left alone.",
    forms: ["leave", "left", "left"],
    formUsed: "V3 (состояние)",
    ru: "Он остался один",
    film: "Cast Away",
    character: "",
  },
  {
    example: "Think about it.",
    forms: ["think", "thought", "thought"],
    formUsed: "V1 (Present / Base)",
    ru: "Подумай об этом",
    film: "The Matrix",
    character: "Морфеус",
  },
  {
    example: "I thought you were dead.",
    forms: ["think", "thought", "thought"],
    formUsed: "V2 (Past)",
    ru: "Я думал, что ты мёртв",
    film: "Inception",
    character: "Кобб",
  },
  {
    example: "The idea is thought through.",
    forms: ["think", "thought", "thought"],
    formUsed: "V3 (состояние)",
    ru: "Идея продумана",
    film: "A Beautiful Mind",
    character: "",
  },
  {
    example: "Come with me.",
    forms: ["come", "came", "come"],
    formUsed: "V1 (Present / Base)",
    ru: "Пойдём со мной",
    film: "Terminator 2: Judgment Day",
    character: "Терминатор (Арнольд Шварценеггер)",
  },
  {
    example: "You came back.",
    forms: ["come", "came", "come"],
    formUsed: "V2 (Past)",
    ru: "Ты вернулся",
    film: "Interstellar",
    character: "Купер (Мэттью Макконахи)",
  },
  {
    example: "Winter has come.",
    forms: ["come", "came", "come"],
    formUsed: "V3 (состояние)",
    ru: "Зима наступила",
    film: "Game of Thrones",
    character: "",
  },
  {
    example: "Find the truth.",
    forms: ["find", "found", "found"],
    formUsed: "V1 (Present / Base)",
    ru: "Найди правду",
    film: "Se7en",
    character: "детектив Сомерсет",
  },
  {
    example: "I found the answer.",
    forms: ["find", "found", "found"],
    formUsed: "V2 (Past)",
    ru: "Я нашёл ответ",
    film: "The Da Vinci Code",
    character: "Роберт Лэнгдон",
  },
  {
    example: "The evidence is found.",
    forms: ["find", "found", "found"],
    formUsed: "V3 (состояние)",
    ru: "Доказательство найдено",
    film: "Spotlight",
    character: "",
  },
  {
    example: "Show me the money.",
    forms: ["show", "showed", "shown"],
    formUsed: "V1 (Present / Base)",
    ru: "Покажи деньги",
    film: "Jerry Maguire",
    character: "Род Тидвелл",
  },
  {
    example: "He showed no mercy.",
    forms: ["show", "showed", "shown"],
    formUsed: "V2 (Past)",
    ru: "Он не проявил пощады",
    film: "Gladiator",
    character: "Коммод",
  },
  {
    example: "The truth is shown.",
    forms: ["show", "showed", "shown"],
    formUsed: "V3 (состояние)",
    ru: "Правда раскрыта",
    film: "V for Vendetta",
    character: "",
  },
  {
    example: "I take responsibility for my actions.",
    forms: ["take", "took", "taken"],
    formUsed: "V1 (Present / Base)",
    ru: "Я беру ответственность за свои действия",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "I took the money and ran.",
    forms: ["take", "took", "taken"],
    formUsed: "V2 (Past)",
    ru: "Я взял деньги и убежал",
    film: "Pulp Fiction",
    character: "Pumpkin (Ringo)",
  },
  {
    example: "The hostages are taken.",
    forms: ["take", "took", "taken"],
    formUsed: "V3 (состояние)",
    ru: "Заложники захвачены",
    film: "Taken",
    character: "Bryan Mills",
  },
  {
    example: "I won't let you down.",
    forms: ["let", "let", "let"],
    formUsed: "V1 (Present / Base)",
    ru: "Я тебя не подведу",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "He let her go.",
    forms: ["let", "let", "let"],
    formUsed: "V2 (Past)",
    ru: "Он отпустил её",
    film: "Titanic",
    character: "Jack Dawson",
  },
  {
    example: "You are let inside.",
    forms: ["let", "let", "let"],
    formUsed: "V3 (состояние)",
    ru: "Тебя впустили",
    film: "Harry Potter and the Philosopher's Stone",
    character: "Rubeus Hagrid",
  },
  {
    example: "I set my own rules.",
    forms: ["set", "set", "set"],
    formUsed: "V1 (Present / Base)",
    ru: "Я устанавливаю свои правила",
    film: "Iron Man",
    character: "Tony Stark",
  },
  {
    example: "He set the plan in motion.",
    forms: ["set", "set", "set"],
    formUsed: "V2 (Past)",
    ru: "Он привёл план в действие",
    film: "The Dark Knight",
    character: "Joker",
  },
  {
    example: "The trap is set.",
    forms: ["set", "set", "set"],
    formUsed: "V3 (состояние)",
    ru: "Ловушка установлена",
    film: "Home Alone",
    character: "Kevin McCallister",
  },
  {
    example: "I read everything I can find.",
    forms: ["read", "read", "read"],
    formUsed: "V1 (Present / Base)",
    ru: "Я читаю всё, что могу найти",
    film: "Harry Potter and the Philosopher's Stone",
    character: "Hermione Granger",
  },
  {
    example: "I read[red] your file.",
    forms: ["read", "read", "read"],
    formUsed: "V2 (Past)",
    ru: "Я прочитал твоё досье",
    film: "The Matrix",
    character: "Agent Smith",
  },
  {
    example: "The message is read[red].",
    forms: ["read", "read", "read"],
    formUsed: "V3 (состояние)",
    ru: "Сообщение прочитано",
    film: "Sherlock Holmes",
    character: "Sherlock Holmes",
  },
  {
    example: "I light the fire every night.",
    forms: ["light", "lit", "lit"],
    formUsed: "V1 (Present / Base)",
    ru: "Я зажигаю огонь каждую ночь",
    film: "The Revenant",
    character: "Hugh Glass",
  },
  {
    example: "He lit the match.",
    forms: ["light", "lit", "lit"],
    formUsed: "V2 (Past)",
    ru: "Он зажёг спичку",
    film: "The Dark Knight",
    character: "Joker",
  },
  {
    example: "The room is lit.",
    forms: ["light", "lit", "lit"],
    formUsed: "V3 (состояние)",
    ru: "Комната освещена",
    film: "John Wick",
    character: "John Wick",
  },
  {
    example: "I keep my promises.",
    forms: ["keep", "kept", "kept"],
    formUsed: "V1 (Present / Base)",
    ru: "Я держу свои обещания",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "I kept the secret.",
    forms: ["keep", "kept", "kept"],
    formUsed: "V2 (Past)",
    ru: "Я сохранил секрет",
    film: "Harry Potter and the Deathly Hallows: Part 2",
    character: "Severus Snape",
  },
  {
    example: "The door is kept locked.",
    forms: ["keep", "kept", "kept"],
    formUsed: "V3 (состояние)",
    ru: "Дверь держат запертой",
    film: "Jurassic Park",
    character: "John Hammond",
  },
  {
    example: "I learn fast.",
    forms: ["learn", "learnt", "learnt"],
    formUsed: "V1 (Present / Base)",
    ru: "Я быстро учусь",
    film: "The Matrix",
    character: "Neo",
  },
  {
    example: "I learnt the truth.",
    forms: ["learn", "learnt", "learnt"],
    formUsed: "V2 (Past)",
    ru: "Я узнал правду",
    film: "Star Wars: Episode V – The Empire Strikes Back",
    character: "Luke Skywalker",
  },
  {
    example: "The lesson is learnt.",
    forms: ["learn", "learnt", "learnt"],
    formUsed: "V3 (состояние)",
    ru: "Урок усвоен",
    film: "Batman Begins",
    character: "Bruce Wayne",
  },
  {
    example: "I can do this all day.",
    forms: ["can", "could", "could"],
    formUsed: "V1 (Present / Base)",
    ru: "Я могу делать это весь день",
    film: "Captain America: The First Avenger",
    character: "Steve Rogers",
  },
  {
    example: "I could save her.",
    forms: ["can", "could", "could"],
    formUsed: "V2 (Past)",
    ru: "Я мог её спасти",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "It could be done.",
    forms: ["can", "could", "could"],
    formUsed: "V3 (состояние)",
    ru: "Это могло быть сделано",
    film: "Inception",
    character: "Dom Cobb",
  },
  {
    example: "I may be able to help you.",
    forms: ["may", "might", "might"],
    formUsed: "V1 (Present / Base)",
    ru: "Возможно, я смогу тебе помочь",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Gandalf",
  },
  {
    example: "It might work.",
    forms: ["may", "might", "might"],
    formUsed: "V2 (Past)",
    ru: "Это могло бы сработать",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "It might be done.",
    forms: ["may", "might", "might"],
    formUsed: "V3 (состояние)",
    ru: "Это могло быть сделано",
    film: "Inception",
    character: "Dom Cobb",
  },
  {
    example: "I get what you mean.",
    forms: ["get", "got", "got"],
    formUsed: "V1 (Present / Base)",
    ru: "Я понимаю, что ты имеешь в виду",
    film: "The Matrix",
    character: "Neo",
  },
  {
    example: "I got the message.",
    forms: ["get", "got", "got"],
    formUsed: "V2 (Past)",
    ru: "Я получил сообщение",
    film: "John Wick",
    character: "John Wick",
  },
  {
    example: "The job is got.",
    forms: ["get", "got", "got"],
    formUsed: "V3 (состояние)",
    ru: "Работа получена",
    film: "The Wolf of Wall Street",
    character: "Jordan Belfort",
  },
  {
    example: "I have a plan.",
    forms: ["have", "had", "had"],
    formUsed: "V1 (Present / Base)",
    ru: "У меня есть план",
    film: "The Dark Knight",
    character: "Joker",
  },
  {
    example: "I had a choice.",
    forms: ["have", "had", "had"],
    formUsed: "V2 (Past)",
    ru: "У меня был выбор",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "The problem is had.",
    forms: ["have", "had", "had"],
    formUsed: "V3 (состояние)",
    ru: "Проблема уже имелась",
    film: "The Matrix Reloaded",
    character: "Neo",
  },
  {
    example: "I hear everything.",
    forms: ["hear", "heard", "heard"],
    formUsed: "V1 (Present / Base)",
    ru: "Я слышу всё",
    film: "The Dark Knight",
    character: "Lucius Fox",
  },
  {
    example: "I heard a noise.",
    forms: ["hear", "heard", "heard"],
    formUsed: "V2 (Past)",
    ru: "Я услышал шум",
    film: "A Quiet Place",
    character: "Lee Abbott",
  },
  {
    example: "The signal is heard.",
    forms: ["hear", "heard", "heard"],
    formUsed: "V3 (состояние)",
    ru: "Сигнал услышан",
    film: "Interstellar",
    character: "Cooper",
  },
  {
    example: "I say we go now.",
    forms: ["say", "said", "said"],
    formUsed: "V1 (Present / Base)",
    ru: "Я говорю, что нам нужно идти сейчас",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Aragorn",
  },
  {
    example: "He said too much.",
    forms: ["say", "said", "said"],
    formUsed: "V2 (Past)",
    ru: "Он сказал слишком много",
    film: "The Godfather",
    character: "Michael Corleone",
  },
  {
    example: "It is said that he never sleeps.",
    forms: ["say", "said", "said"],
    formUsed: "V3 (состояние)",
    ru: "Говорят, что он никогда не спит",
    film: "John Wick",
    character: "Viggo Tarasov",
  },
  {
    example: "I tell the truth.",
    forms: ["tell", "told", "told"],
    formUsed: "V1 (Present / Base)",
    ru: "Я говорю правду",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "I told you everything.",
    forms: ["tell", "told", "told"],
    formUsed: "V2 (Past)",
    ru: "Я рассказал тебе всё",
    film: "Titanic",
    character: "Rose DeWitt Bukater",
  },
  {
    example: "The story is told.",
    forms: ["tell", "told", "told"],
    formUsed: "V3 (состояние)",
    ru: "История рассказана",
    film: "Forrest Gump",
    character: "Forrest Gump",
  },
  {
    example: "I begin when you're ready.",
    forms: ["begin", "began", "begun"],
    formUsed: "V1 (Present / Base)",
    ru: "Я начинаю, когда ты готов",
    film: "Inception",
    character: "Dom Cobb",
  },
  {
    example: "It all began here.",
    forms: ["begin", "began", "begun"],
    formUsed: "V2 (Past)",
    ru: "Всё началось здесь",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Galadriel",
  },
  {
    example: "The game has begun.",
    forms: ["begin", "began", "begun"],
    formUsed: "V3 (состояние)",
    ru: "Игра началась",
    film: "Sherlock Holmes",
    character: "Sherlock Holmes",
  },
  {
    example: "I do what I have to do.",
    forms: ["do", "did", "done"],
    formUsed: "V1 (Present / Base)",
    ru: "Я делаю то, что должен",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "I did everything right.",
    forms: ["do", "did", "done"],
    formUsed: "V2 (Past)",
    ru: "Я всё сделал правильно",
    film: "Breaking Bad",
    character: "Walter White",
  },
  {
    example: "The job is done.",
    forms: ["do", "did", "done"],
    formUsed: "V3 (состояние)",
    ru: "Работа завершена",
    film: "John Wick",
    character: "John Wick",
  },
  {
    example: "I give you my word.",
    forms: ["give", "gave", "given"],
    formUsed: "V1 (Present / Base)",
    ru: "Я даю тебе своё слово",
    film: "The Lord of the Rings: The Two Towers",
    character: "Aragorn",
  },
  {
    example: "I gave him a chance.",
    forms: ["give", "gave", "given"],
    formUsed: "V2 (Past)",
    ru: "Я дал ему шанс",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "The order is given.",
    forms: ["give", "gave", "given"],
    formUsed: "V3 (состояние)",
    ru: "Приказ отдан",
    film: "Gladiator",
    character: "Maximus",
  },
  {
    example: "I go where I'm needed.",
    forms: ["go", "went", "gone"],
    formUsed: "V1 (Present / Base)",
    ru: "Я иду туда, где я нужен",
    film: "The Dark Knight",
    character: "Batman (Bruce Wayne)",
  },
  {
    example: "I went back for you.",
    forms: ["go", "went", "gone"],
    formUsed: "V2 (Past)",
    ru: "Я вернулся за тобой",
    film: "Titanic",
    character: "Jack Dawson",
  },
  {
    example: "He is gone.",
    forms: ["go", "went", "gone"],
    formUsed: "V3 (состояние)",
    ru: "Он ушёл",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Aragorn",
  },
  {
    example: "I know what you did.",
    forms: ["know", "knew", "known"],
    formUsed: "V1 (Present / Base)",
    ru: "Я знаю, что ты сделал",
    film: "Sherlock Holmes",
    character: "Sherlock Holmes",
  },
  {
    example: "I knew it.",
    forms: ["know", "knew", "known"],
    formUsed: "V2 (Past)",
    ru: "Я так и знал",
    film: "The Matrix",
    character: "Neo",
  },
  {
    example: "It is known.",
    forms: ["know", "knew", "known"],
    formUsed: "V3 (состояние)",
    ru: "Это известно",
    film: "Game of Thrones",
    character: "Khal Drogo",
  },
  {
    example: "I see dead people.",
    forms: ["see", "saw", "seen"],
    formUsed: "V1 (Present / Base)",
    ru: "Я вижу мёртвых людей",
    film: "The Sixth Sense",
    character: "Cole Sear",
  },
  {
    example: "I saw him.",
    forms: ["see", "saw", "seen"],
    formUsed: "V2 (Past)",
    ru: "Я видел его",
    film: "The Lord of the Rings: The Fellowship of the Ring",
    character: "Frodo Baggins",
  },
  {
    example: "He is seen as a hero.",
    forms: ["see", "saw", "seen"],
    formUsed: "V3 (состояние)",
    ru: "Его считают героем",
    film: "Spider-Man",
    character: "Peter Parker",
  },
  {
    example: "I write my own story.",
    forms: ["write", "wrote", "written"],
    formUsed: "V1 (Present / Base)",
    ru: "Я пишу свою собственную историю",
    film: "Joker",
    character: "Arthur Fleck",
  },
  {
    example: "I wrote it down.",
    forms: ["write", "wrote", "written"],
    formUsed: "V2 (Past)",
    ru: "Я это записал",
    film: "Sherlock Holmes",
    character: "Dr. John Watson",
  },
  {
    example: "The letter is written.",
    forms: ["write", "wrote", "written"],
    formUsed: "V3 (состояние)",
    ru: "Письмо написано",
    film: "Pride & Prejudice",
    character: "Mr. Darcy",
  },
];

// ── Vocabulary · S01E01 · Your Friends & Neighbors · segment 1 (00:00–10:00) ──
window.VOCAB_DECK = [
  { type: 'vocab', phrase: 'introspection',  translation: 'самоанализ',                     context: "I wasn't generally the kind of guy who did a lot of introspection.",     level: 'B2', time: '01:40' },
  { type: 'vocab', phrase: 'fleeting',       translation: 'мимолётный',                     context: 'Catch a fleeting glimpse.',                                              level: 'B2', time: '01:53' },
  { type: 'vocab', phrase: 'swirling',       translation: 'закружившийся, вихрящийся',      context: 'The swirling hot mess of my life.',                                      level: 'B2', time: '01:58' },
  { type: 'vocab', phrase: 'promotion',      translation: 'повышение',                      context: 'Big promotion, boy!',                                                    level: 'B1', time: '02:25' },
  { type: 'vocab', phrase: 'recognize',      translation: 'узнать',                         context: "I didn't recognize you.",                                                level: 'B1', time: '02:50' },
  { type: 'vocab', phrase: 'fanboy',         translation: 'фанатик, фанбой',               context: 'The Patrick Bateman fanboys over there.',                                level: 'C1', time: '02:56' },
  { type: 'vocab', phrase: 'occupied',       translation: 'занятой, при деле',             context: 'It might be better if I looked occupied.',                               level: 'B2', time: '02:59' },
  { type: 'vocab', phrase: 'impatient',      translation: 'нетерпеливый',                   context: 'I got impatient.',                                                       level: 'B2', time: '03:04' },
  { type: 'vocab', phrase: 'single',         translation: 'холостой',                       context: "I'm recently single.",                                                   level: 'B1', time: '03:06' },
  { type: 'vocab', phrase: 'married',        translation: 'женат/замужем',                 context: 'You were married?',                                                      level: 'B1', time: '03:15' },
  { type: 'vocab', phrase: 'convention',     translation: 'условность, традиция',          context: 'The conventions of marriage.',                                           level: 'B2', time: '03:30' },
  { type: 'vocab', phrase: 'segment',        translation: 'сегмент, часть',                context: 'An entire segment of the population.',                                   level: 'B2', time: '03:37' },
  { type: 'vocab', phrase: 'harmony',        translation: 'гармония',                       context: 'Peace of mind, harmony.',                                                level: 'B2', time: '03:50' },
  { type: 'vocab', phrase: 'achieve',        translation: 'достичь',                        context: 'How many of them have you achieved?',                                    level: 'B1', time: '03:52' },
  { type: 'vocab', phrase: 'rules',          translation: 'правила',                        context: 'Maybe you should rethink the rules.',                                    level: 'B1', time: '03:56' },
  { type: 'vocab', phrase: 'irony',          translation: 'ирония',                         context: 'The irony is, I was morbidly obese.',                                    level: 'B2', time: '04:26' },
  { type: 'vocab', phrase: 'morbidly',       translation: 'болезненно (о массе)',           context: 'I was morbidly obese as a teenager.',                                    level: 'C1', time: '04:26' },
  { type: 'vocab', phrase: 'obese',          translation: 'страдающий ожирением',           context: 'I was morbidly obese.',                                                  level: 'B2', time: '04:26' },
  { type: 'vocab', phrase: 'narcissistic',   translation: 'нарциссический',                context: 'Narcissistic man-boys.',                                                 level: 'B2', time: '04:59' },
  { type: 'vocab', phrase: 'antidote',       translation: 'противоядие',                    context: 'Looks like the perfect antidote.',                                        level: 'B2', time: '05:04' },
  { type: 'vocab', phrase: 'freedom',        translation: 'свобода',                        context: 'I have money, you have freedom.',                                         level: 'B1', time: '05:18' },
  { type: 'vocab', phrase: 'decade',         translation: 'десятилетие',                    context: 'Two decades more worth of stories.',                                      level: 'B1', time: '05:27' },
  { type: 'vocab', phrase: 'reckless',       translation: 'безрассудный',                   context: 'The kind of reckless immediacy.',                                         level: 'B2', time: '05:32' },
  { type: 'vocab', phrase: 'shaky',          translation: 'шаткий',                         context: 'Things can start to get a little shaky.',                                 level: 'B2', time: '05:45' },
  { type: 'vocab', phrase: 'experience',     translation: 'опыт',                           context: "One of life's great experiences.",                                        level: 'B1', time: '05:51' },
  { type: 'vocab', phrase: 'stunning',       translation: 'потрясающий',                    context: "You'll still be stunning.",                                               level: 'B1', time: '05:52' },
  { type: 'vocab', phrase: 'prostate',       translation: 'простата',                       context: "My prostate's gonna do what it does.",                                    level: 'B2', time: '06:18' },
  { type: 'vocab', phrase: 'insecure',       translation: 'неуверенный в себе',            context: 'Are you that insecure?',                                                 level: 'B2', time: '06:29' },
  { type: 'vocab', phrase: 'self-esteem',    translation: 'самооценка',                     context: 'A very strange mix of confidence and low self-esteem.',                   level: 'B2', time: '06:38' },
  { type: 'vocab', phrase: 'jealous',        translation: 'ревнивый',                       context: "I'll be the jealous, old troll.",                                         level: 'B2', time: '06:40' },
  { type: 'vocab', phrase: 'restless',       translation: 'беспокойный',                    context: 'A restless woman in her sexual prime.',                                   level: 'B2', time: '06:42' },
  { type: 'vocab', phrase: 'consumed',       translation: 'поглощённый',                    context: 'Consumed by this nagging fear.',                                          level: 'B2', time: '06:44' },
  { type: 'vocab', phrase: 'nagging',        translation: 'ноющий, не дающий покоя',       context: 'This nagging fear.',                                                     level: 'B2', time: '06:44' },
  { type: 'vocab', phrase: 'utterly',        translation: 'совершенно, абсолютно',          context: 'Spent completely and utterly alone.',                                      level: 'C1', time: '06:49' },
  { type: 'vocab', phrase: 'rebuttal',       translation: 'возражение, опровержение',       context: 'A full-throated rebuttal.',                                               level: 'B2', time: '07:02' },
  { type: 'vocab', phrase: 'copacetic',      translation: 'всё в полном порядке',           context: 'When things are, you know, copacetic.',                                   level: 'C1', time: '08:52' },
  { type: 'vocab', phrase: 'jumbo',          translation: 'крупный (об ипотеке)',           context: '30-year jumbo at four and a half percent.',                              level: 'C1', time: '09:00' },
  { type: 'vocab', phrase: 'leveraged',      translation: 'закредитованный',               context: "You're leveraged.",                                                      level: 'C1', time: '09:29' },
  { type: 'vocab', phrase: 'naive',          translation: 'наивный',                        context: 'Naive plans you may have once had.',                                       level: 'C1', time: '09:40' },
];

// ── Phrasal verbs · S01E01 · Your Friends & Neighbors · segment 1 (00:00–10:00) ──
window.PHRASAL_DECK = [
  { type: 'phrasal', phrase: "wake up", time: "01:45", translation: "проснуться", context: "I wasn't the kind of guy who woke up on the floor of someone else's house.", contextTranslation: "Я был не из тех парней, кто просыпается на полу в чужом доме.", literalTranslation: "«будить вверх» — глагол wake (будить) + up подчёркивает выход из состояния сна.", history: "Up давно обозначает активацию, переход в бодрствование (light up, fire up, wake up). Возникло в среднеанглийском." },
  { type: 'phrasal', phrase: "fall into", time: "01:49", translation: "упасть в", context: "...before falling into the pool.", contextTranslation: "...перед тем как упасть в бассейн.", literalTranslation: "«падать внутрь».", history: "Прямое сочетание fall + into. Используется буквально (in water) и метафорически: fall into a trap, fall into despair." },
  { type: 'phrasal', phrase: "go wrong", time: "02:00", translation: "пойти не так", context: "How the hell everything could go so wrong so fast.", contextTranslation: "Как, чёрт возьми, всё могло пойти настолько не так и так быстро.", literalTranslation: "«идти неправильно».", history: "Конструкция go + adjective (go bad, go crazy). Глагол go обозначает переход в состояние." },
  { type: 'phrasal', phrase: "come on", time: "02:13", translation: "давай / да ладно", context: "Lloyd, come on. Let's do shots.", contextTranslation: "Ллойд, давай. Накатим по шоту.", literalTranslation: "«идти на, наступать».", history: "От буквального «приближаться» (come on stage). В разговорной речи XX века — побуждение «давай!» или возглас несогласия." },
  { type: 'phrasal', phrase: "tip off", time: "02:36", translation: "подсказать, слить инфу", context: "Bartender tipped me off.", contextTranslation: "Бармен мне подсказал.", literalTranslation: "«отщёлкнуть кончик».", history: "От tip (намёк) — торговый сленг XIX века: дать «кончик» информации. Часто в криминальном контексте." },
  { type: 'phrasal', phrase: "come over", time: "03:02", translation: "подойти / заглянуть", context: "It looked like you were going to come over to me.", contextTranslation: "Казалось, ты сейчас подойдёшь ко мне.", literalTranslation: "«идти через, поверх».", history: "Over подразумевает преодоление расстояния. Используется со старoанглийского для движения к говорящему." },
  { type: 'phrasal', phrase: "be wrapped up in", time: "03:30", translation: "быть поглощённым", context: "You've been wrapped up in the conventions of marriage.", contextTranslation: "Ты с головой ушла в условности брака.", literalTranslation: "«быть завёрнутым в».", history: "Метафора от «завернуть подарок»: человек окутан темой и не может из неё выйти." },
  { type: 'phrasal', phrase: "turn out", time: "04:23", translation: "оказаться", context: "It turned out he liked fat hookers.", contextTranslation: "Оказалось, ему нравились толстые проститутки.", literalTranslation: "«повернуть наружу».", history: "Из театрального жаргона XIX века (turn out — выходить на сцену). Стало означать «обнаружиться, проявиться»." },
  { type: 'phrasal', phrase: "happen upon", time: "04:31", translation: "случайно наткнуться", context: "After I happened upon his browsing history...", contextTranslation: "После того как я случайно наткнулась на его историю браузера...", literalTranslation: "«случиться на».", history: "Литературный оборот XVI–XVII вв. Upon = on в более формальной речи. Сейчас звучит изысканно." },
  { type: 'phrasal', phrase: "skip ahead", time: "05:42", translation: "перескочить вперёд", context: "Skip ahead ten years.", contextTranslation: "Перескочим вперёд на десять лет.", literalTranslation: "«прыгать вперёд».", history: "Skip — прыгать с пропуском. Часто в нарративе: skip ahead in a movie, skip a chapter." },
  { type: 'phrasal', phrase: "miss out on", time: "05:49", translation: "упустить", context: "Have I missed out on one of life's great experiences?", contextTranslation: "Не упустила ли я один из главных жизненных опытов?", literalTranslation: "«промахнуться насчёт».", history: "Out — выпасть из чего-то, on — о чём-то. Идиома XIX века о пропущенных возможностях." },
  { type: 'phrasal', phrase: "take care of", time: "06:15", translation: "заботиться о", context: "No matter how well I take care of myself.", contextTranslation: "Как бы хорошо я о себе ни заботился.", literalTranslation: "«взять заботу о».", history: "Care как «забота» — древнеанглийское слово. Конструкция take care появилась в среднеанглийском." },
  { type: 'phrasal', phrase: "come up with", time: "06:53", translation: "придумать", context: "When did you come up with all of that?", contextTranslation: "Когда ты всё это придумал?", literalTranslation: "«прийти вверх с».", history: "Метафора: идея «всплывает» (comes up) из глубин сознания, и ты приходишь с ней (with) к собеседнику." },
  { type: 'phrasal', phrase: "work (one's) ass off", time: "08:39", translation: "пахать как проклятый", context: "You work your asses off and you dig yourselves out.", contextTranslation: "Вы пашете как проклятые и выбираетесь из ямы.", literalTranslation: "«работать, пока задницу не сотрёшь».", history: "Грубая идиома XX века. Гипербола: работаешь так, что «отрабатываешь» части тела (work your fingers to the bone)." },
  { type: 'phrasal', phrase: "dig (oneself) out", time: "08:39", translation: "выбраться из проблем", context: "You dig yourselves out.", contextTranslation: "Вы выкарабкиваетесь.", literalTranslation: "«выкопать себя наружу».", history: "Метафора горнодобывающего труда — выкопаться из ямы или долгов. Старая англоамериканская идиома." },
  { type: 'phrasal', phrase: "start out", time: "09:42", translation: "начинать (путь, карьеру)", context: "...the things that mattered when you were starting out.", contextTranslation: "...вещи, которые были важны для тебя в начале пути.", literalTranslation: "«стартовать наружу».", history: "Out — выход в большой мир, начало путешествия (set out, head out). Используется с XIX века." },
];

// ── Idioms · S01E01 · Your Friends & Neighbors · segment 1 (00:00–10:00) ──
window.IDIOM_DECK = [
  { type: 'idiom', phrase: "out of the corner of one's eye", time: "01:56", translation: "краем глаза", context: "Catch a fleeting glimpse, out of the corner of my eye.", contextTranslation: "Поймать мимолётный взгляд краем глаза.", literalTranslation: "«из угла глаза».", history: "Древняя идиома: периферийное зрение = «угол глаза». Существует во многих языках в похожей форме." },
  { type: 'idiom', phrase: "a hot mess", time: "01:58", translation: "полный бардак, хаос", context: "...the swirling hot mess of my life.", contextTranslation: "...закружившийся хаос моей жизни.", literalTranslation: "«горячий беспорядок».", history: "Идиома южных штатов США XIX века: буквально «горячая каша». В 2000-х стала вирусной через поп-культуру." },
  { type: 'idiom', phrase: "how the hell", time: "02:00", translation: "как, чёрт возьми", context: "How the hell everything could go so wrong so fast.", contextTranslation: "Как, чёрт возьми, всё могло пойти так не так и так быстро.", literalTranslation: "«как ад».", history: "The hell — усилитель вопросов, разговорное смягчение более грубых форм. С XIX века популярно в AmE." },
  { type: 'idiom', phrase: "have no game", time: "03:11", translation: "не уметь клеить, нет харизмы", context: "I'm afraid I don't have much game.", contextTranslation: "Боюсь, я не очень умею в эти игры.", literalTranslation: "«не иметь игры».", history: "Game = «навыки соблазнения» — из афроамериканского сленга 1970–80-х (хип-хоп). Сейчас мейнстрим." },
  { type: 'idiom', phrase: "different strokes", time: "04:24", translation: "у каждого свой вкус", context: "Different strokes.", contextTranslation: "У каждого свои причуды.", literalTranslation: "«разные удары/гребки».", history: "Сокращение от «Different strokes for different folks» — фраза Мухаммеда Али (1960-е). Также — ситком 1978 года." },
  { type: 'idiom', phrase: "by and large", time: "04:50", translation: "в общем и целом", context: "By and large, guys your age are idiots.", contextTranslation: "В целом, парни твоего возраста — идиоты.", literalTranslation: "«у ветра и в полную ширь» (морск.).", history: "Морская идиома XVII века: by — круто к ветру, large — с попутным. Оба варианта = в любых условиях." },
  { type: 'idiom', phrase: "out of one's depth", time: "04:59", translation: "не по зубам, не в своей лиге", context: "Narcissistic man-boys far out of their depth with you.", contextTranslation: "Нарциссы-мальчишки, которым ты не по зубам.", literalTranslation: "«вне своей глубины».", history: "Морская метафора: ушёл туда, где дна не достать. С XIX века — о ситуациях, где не хватает компетенции." },
  { type: 'idiom', phrase: "in the moment", time: "05:29", translation: "в моменте, здесь и сейчас", context: "You live your life in the moment.", contextTranslation: "Ты живёшь моментом.", literalTranslation: "«в моменте».", history: "Из театрального жаргона (техника Станиславского). С 1990-х мейнстрим, особенно в контексте mindfulness." },
  { type: 'idiom', phrase: "kick it", time: "06:22", translation: "сыграть в ящик (умереть)", context: "What your life looks like after I kick it.", contextTranslation: "Как будет выглядеть твоя жизнь после того, как я отброшу копыта.", literalTranslation: "«пнуть это».", history: "Сокращение от kick the bucket. Происхождение спорно: либо повешение (выбивали ведро), либо забой свиней." },
  { type: 'idiom', phrase: "get laid", time: "07:05", translation: "переспать с кем-то", context: "Honestly, man, I was just looking to get laid.", contextTranslation: "Если честно, я просто хотел перепихнуться.", literalTranslation: "«быть уложенным».", history: "Lay = положить (в т.ч. в постель). Грубый сленг США 1930-х. Get laid — пассивная форма «получить секс»." },
  { type: 'idiom', phrase: "come to mind", time: "07:14", translation: "приходить на ум", context: "None come to mind.", contextTranslation: "Ни одна не приходит в голову.", literalTranslation: "«прийти в ум».", history: "Mind как «вместилище мыслей» — древнегерманская концепция. Идиома существует с XIV века." },
  { type: 'idiom', phrase: "right out of college", time: "08:01", translation: "сразу после колледжа", context: "You land a job right out of college at a major firm.", contextTranslation: "Ты получаешь работу сразу после колледжа в крупной фирме.", literalTranslation: "«прямо из колледжа».", history: "Right = «прямо, сразу». Стандартный американский нарратив о начале карьеры." },
  { type: 'idiom', phrase: "a cog in a wheel", time: "08:04", translation: "винтик в системе", context: "You're just another cog in a very large wheel.", contextTranslation: "Ты просто очередной винтик в огромном колесе.", literalTranslation: "«зубец в колесе».", history: "Промышленная метафора XIX века: каждый зубец важен, но взаимозаменяем. Символ обезличенности." },
  { type: 'idiom', phrase: "get a foot in the door", time: "08:05", translation: "пробиться, зацепиться", context: "You've got your foot in the door.", contextTranslation: "Ты уже зацепился (получил шанс).", literalTranslation: "«вставить ногу в дверь».", history: "От коммивояжёров XIX–XX вв.: вставляли ногу, чтобы дверь не закрыли. Первый шаг к сделке." },
  { type: 'idiom', phrase: "dead broke", time: "08:22", translation: "без копейки", context: "You're dead broke, but there's two of you now.", contextTranslation: "Вы без гроша, но теперь вас двое.", literalTranslation: "«мертвецки сломленный».", history: "Dead — усилитель (dead tired, dead serious). Broke = «сломленный» финансово — сленг XVII века." },
  { type: 'idiom', phrase: "in it together", time: "08:24", translation: "быть в этом вместе", context: "You're in it together and that feels good.", contextTranslation: "Вы в этом вместе, и это приятно.", literalTranslation: "«быть в этом вместе».", history: "Выражение солидарности. Использовалось в военной риторике; стало мемом во время COVID-19." },
  { type: 'idiom', phrase: "big bucks", time: "09:11", translation: "большие деньги", context: "You start earning some big bucks.", contextTranslation: "Ты начинаешь зарабатывать большие бабки.", literalTranslation: "«большие самцы».", history: "Buck = доллар. В колониальной Америке шкуры оленя-самца (buck) служили валютой в торговле с индейцами." },
  { type: 'idiom', phrase: "a fancy way of saying", time: "09:29", translation: "громкое слово вместо простого", context: "A fancy way of saying you've got something to show for your efforts.", contextTranslation: "Красивый способ сказать, что у тебя есть что показать.", literalTranslation: "«вычурный способ говорить».", history: "Используется иронично: замена простого слова на пышное. XIX век." },
  { type: 'idiom', phrase: "lose sight of", time: "09:38", translation: "упустить из виду", context: "You've lost sight of whatever naive plans you may have once had.", contextTranslation: "Ты потерял из виду те наивные планы, что когда-то имел.", literalTranslation: "«потерять видение чего-то».", history: "Морская идиома: lose sight of land — потерять землю из виду. С XV века метафорически о целях." },
  { type: 'idiom', phrase: "what's the point", time: "09:49", translation: "в чём смысл", context: "Really, what's the point of all this shit?", contextTranslation: "В чём вообще смысл всей этой херни?", literalTranslation: "«в чём суть/острие».", history: "Point — буквально кончик/острие, метафорически «суть». Используется с XIV века." },
];

// ── Segment 1 · combined deck sorted by film timestamp ──
;(function () {
  function tsToSecs(t) { const [m, s] = t.split(':').map(Number); return m * 60 + s; }
  window.SEGMENT1_DECK = [
    ...window.VOCAB_DECK,
    ...window.PHRASAL_DECK,
    ...window.IDIOM_DECK,
  ].sort((a, b) => tsToSecs(a.time) - tsToSecs(b.time));
}());
